### PR TITLE
reindent code to be consistent

### PR DESCRIPTION
**Pull request by JaapWijnen**
I reindented the code since some of it was using 2 spaces and other parts were using 4 spaces

### CODE REVIEW

**Comment by philipturner** [comment]
@JaapWijnen how about keep it at 2 spaces for now to reduce code churn and divergence? Setting it to 4 spaces may set some comments out of alignment. This code is formatted with 2-space tabs and a 100-character line limit. Some comments are formatted to 80-character limits, such as the very long comment in S4TF explaining `_TensorElementLiteral`. If we import code from S4TF then we'll have to constantly reformat it to 4 spaces.

The initial contributions to this repo are like patches to an existing code base. If this expands into something much larger, setting a new formatting style would become more appropriate. On the other hand, an entirely new repository, such as the "Matrix" library's Swift package, could definitely start out with 4-space tabs and no line limit.

**Comment by philipturner** [comment]
We should also follow other pre-existing code conventions, such as designing for ABI stability (hence the `@frozen` on structs) and minimizing the chance for API breakage in dependent repositories. For example, don't arbitrarily change `@inlinable` to `@usableFromInline` or `@inline(__always)` to `@inline(never)` without explaining the rationale and having other contributors review it. This seems nit-picky, but reducing code churn makes maintaining the code base easier in the long-term.

**Comment by JaapWijnen** [comment]
Hm I'd argue to stay in line with all apple's open source packages (and generally all Swift packages) reindenting is a simple Ctrl + I and ok comments would be a little more work if really necessary. 
Ok will keep those markers in mind, I thought we'd get some basics working and break and improve api often at the start since we're not perse following 100% of tensorflow's api. And then do a pass where we keep in mind ABI stability and API breakage

**Comment by philipturner** [comment]
> Ok will keep those markers in mind, I thought we'd get some basics working and break and improve api often at the start since we're not perse following 100% of tensorflow's api.

I agree that we can deviate from TensorFlow's API. I'm just uneasy about using 4 spaces instead of 2 spaces at the moment. I originally wanted this to transfer back into possession of the S4TF organization, where it would keep the same style conventions as other repositories there.

The SNWG had a discussion on Slack and agreed to use 4 spaces with no character limit for their repositories. I prefer to use 2 spaces and an 80-character limit because it's more accessible, but other members disagreed. I use this convention for all of my recent repositories so I can dual-window on my 120Hz ProMotion screen, so I'm a bit biased.

**Comment by rexmas** [comment]
> I originally wanted this to transfer back into possession of the S4TF organization

I think it depends on if this is still planned. If we are keeping it with this org then I'd say 4, otherwise 2. I'm also in favor of not having too long a discussion about it and going with whatever yall decide, indentation is one of my least favorite topics in programming.

**Comment by philipturner** [comment]
How about we transition to 4 spaces once we're 100% sure it will stay with the `swift-numerics-workgroup` organization? We can leave the door open, but stay with the status quo while things are uncertain.

How about stay with 2 spaces for now, then revisit our decision two months from now?

**Comment by philipturner** [comment]
The reason I wanted the main repository in `swift-numerics-workgroup` is so you can have something "in your name", and not have it entirely revolving around the `s4tf` org. It would also feel bad to disregard the pull request history associated with this GitHub repo, which will rarely be viewed if the head is in `s4tf`. Other than that, it still feels like an extension of the S4TF project.

We can go ahead and rename the repo `swift-shaped-array`, since it will be a core Swift language repo like `swift-numerics` and `swift-atomics`. The `s4tf` fork would be `shaped-array`, because my naming convention is to drop the `swift-` from the alternative repo. I'll put this up for discussion in Slack.

**Comment by rexmas** [comment]
Agree with what you're proposing 👍 will go ahead with the rename.

**Comment by JaapWijnen** [comment]
If we're going that way I agree with what @rexmas metioned regarding that if it's in this org and we're also renaming to apple's way of naming swift packages we'd also follow that style guide regarding code.

**Comment by philipturner** [comment]
@JaapWijnen this may be tangentially related to the last few comments, but swift-numerics and swift-atomics both use 2-space indents and 80-space character limits. Anything considered an extension of the Swift Standard Library uses that convention. Meanwhile, external projects like the Swift Corelibs and SwiftPM project use 4-space tabs. 

I think swift-shaped-array, given its relation to swift-numerics and S4TF (which at one point compiled as part of the Stdlib), should stay 2-spaced for the near future based on precedent alone. Matrix, on the other hand, is more like the Swift Corelibs project and less like part of the Swift Stdlib.

**Comment by philipturner** [comment]
I wouldn’t take mind taking the role of retroactively policing indentation; other contributors can submit PRs using 4 spaces and no character limit. That would put less burden/restriction on contributors.

**Comment by philipturner** [comment]
I'm going to compile a list of each Apple Swift repo, and which indentation it uses. This is going far down a tangent, but we should have all the available data before making a decision.

#### 2 spaces:
- sourcekit-lsp
- swift
- swift-algorithms
- swift-argument-parser
- swift-async-algorithms
- swift-atomics
- swift-collections
- swift-docc
- swift-driver
- swift-experimental-string-processing
- swift-format
- swift-llvm-bindings
- swift-numerics
- swift-protobuf
- swift-stress-tester
- swift-syntax
- swift-system

#### 4 spaces:
- FHIRModels
- swift-cluster-membership
- swift-corelibs-foundation
- swift-corelibs-libdispatch
- swift-corelibs-xctest
- swift-crypto
- swift-distributed-actors
- swift-distributed-tracing
- swift-docc-plugin
- swift-docc-symbolkit
- swift-http-structures-headers
- swift-llbuild2
- swift-log
- swift-markdown
- swift-metrics
- swift-metrics-extras
- swift-nio
- swift-nio-extras
- swift-nio-http2
- swift-nio-ssh
- swift-nio-ssl
- swift-nio-transport-services
- swift-package-collection-generator
- swift-package-manager
- swift-service-discovery
- swift-statsd-client
- swift-system-metrics
- swift-tools-support-async
- swift-tools-support-core
- swift-xcode-playground-support

**Comment by JaapWijnen** [comment]
Oh wow! I'm surprised there's this many repos with 2 spaces! I hadn't noticed. What do you use two switch between indentations between projects? Or do you change the Xcode indentation settings every time (that seems tedious)

**Comment by philipturner** [comment]
Switching between Xcode indentation settings is not that hard. 95% of my work is in 2-spaced projects. The only 4-spaced project I maintain is PythonKit, and even then I use 2-spaced indentation and manually double-tab everything.

However, I often switch between an 80-character and 100-character line limit based on whether I'm modifying S4TF. For Swift-Colab, I have `github.dev` set to 2-spaced 80-characters by default.

**Comment by philipturner** [comment]
If we want numerical computing to be something integrated first-class into the language, we should treat `swift-shaped-array` like an extension of the Standard Library, and other runtime libs defined as extensions to it (`swift-atomics`, `swift-numerics`, `swift-collections`). All of those have 2-spaced indentation. Everything else (including GPU-backed NDArrays and matrix libraries) are not part of the core language itself. They should not be subjected to such strict formatting constraints, and can be 4-spaced.

With that in mind, we could reformat it from a 100-character limit to an 80-character limit, matching other Stdlib extensions. Supermassive comments are generally 80 spaces, so this shouldn't be difficult.

**Comment by rexmas** [comment]
> Everything else (including GPU-backed NDArrays and matrix libraries)

I had assumed that `ShapedArray` was for all intents and purposes going to be our NDArray regardless of backend?

Also, is there an official statement on why apple chooses 2 vs 4 spaces, or is it more or less up to the group that works on that repo? I wouldn't be surprised if it was the latter considering `swift-corelibs-foundation` is 4 spaces while `swift` is 2. Also from experience companies don't care much about indentation and leave it up to repo owners. So imo just pick something. Line length less than 100 I do find personally annoying though, especially with Swift's (albeit good) convention of longer explicit naming, but again, this conversation needs to end at some point so we can move forward.

**Comment by philipturner** [comment]
> I had assumed that ShapedArray was for all intents and purposes going to be our NDArray regardless of backend?

`ShapedArray` is backed by a Swift `Array`, which makes it CPU-only. If we try any layers of indirection or reverting to TensorFlow's multi-backend storage paradigm, it will negatively impact CPU performance. Also, there's not really a way to add explicit asynchronous duplicates of methods, unless you create a new concrete type or insert a second generic parameter into `ShapedArray`.

Even if we used TensorFlow's mechanism of one concrete type for everything (`Tensor`), which was possible because they didn't have to function-color anything as `async`, we'd still need multiple storage modes. We would always have to pass in the device type to initializers, and find a way to dynamically access multiple possible storage backends inside each method call.

I mentioned on the Slack that we could make an `AsyncShapedArray` type, which has all/some methods being asynchronous and dynamically accesses multiple storage types. It has higher CPU-side overhead, but supports multiple backends. The Swift Standard Library (and tightly integrated extensions such as `Atomics`) are agnostic to GPUs/TPUs and only run assembly code on a CPU. We can use protocols they device (like `ElementaryFunctions`) to enhance external libraries that interface with the GPU, but Swift code does not compile into any kind of GPU assembly.

**Comment by philipturner** [comment]
> So imo just pick something. Line length less than 100 I do find personally annoying though, especially with Swift's (albeit good) convention of longer explicit naming, but again, this conversation needs to end at some point so we can move forward.

This spans more than just the issue of indentation. I was envisioning this like an augmentation of `swift-numerics`, which provides CPU-backed functions for transcendental math. `ShapedArray` would be the Swift equivalent of `numpy.ndarray`, which is so baked into the Python numerical computing ecosystem that PythonKit has a [protocol for it](https://github.com/pvieito/PythonKit/blob/master/PythonKit/NumpyConversion.swift).

If our library takes such a role, it will become an industry standard for Swift numerical computing/scientific computing/machine learning libraries. S4TF would use it as a CPU-side window into a tensor's contents; Matrix would use it for extremely low overhead on the CPU, and future Swift libraries would also use it. It would take a similar role to AutoDiff, making the Swift language itself something dedicated to numerical computing.

**Comment by philipturner** [comment]
> Also, is there an official statement on why apple chooses 2 vs 4 spaces, or is it more or less up to the group that works on that repo?

There are other libraries that are "industry standard" and use 4 spaces, such as `swift-nio`. It seems that using 2 spaces will be a significant bottleneck to development, as most external contributors like @JaapWijnen may be acquainted with 4 spaces. We have a pragmatic reason to switch to 4-spaces/no line limit, so I approve of it.

However, I ask that in any other aspect of this project, we take a strict approach to quality assurance and what's in the user-facing API. Unless absolutely necessary, do not expose library internals or trivial functions to the user. This is the design philosophy behind the Swift Stdlib, `swift-atomics`, `swift-numerics`, etc. We should also heavily vet the generated DocC documentation, ensure comments end with periods, etc.

This is my opinion and it's a group effort, so we can take a different path. I feel that I'm speaking too much like an authority and less like a team member. @rexmas do you have any comment or should we ask for this input of other members? If not, I can work on getting this PR and the next one merged.

**Comment by rexmas** [comment]
> AsyncShapedArray

Ah ya, I agree with that route. Would that not make sense to live in this library though too?

> Unless absolutely necessary, do not expose library internals or trivial functions to the user. This is the design philosophy behind the Swift Stdlib, swift-atomics, swift-numerics, etc. We should also heavily vet the generated DocC documentation, ensure comments end with periods, etc.

I'm entirely on the same page as you here, so no worries. It was a mistake to make `debugLog` public.

I didn't mean to imply that my lack of care about indentation means a lack of care about the rest of our code.

> We have a pragmatic reason to switch to 4-spaces/no line limit, so I approve of it.

Ok, let's do that then.

**Comment by philipturner** [comment]
I don’t think accelerator-backed things belong in this library; it’s general purpose because it’s CPU-only and like part of the language itself. Other clients might use ShapedArray for a different purpose than we are. At a minimum, we should postpone the idea of adding AsyncShapedArray.

**Comment by philipturner** [comment]
I’ll open this PR in Xcode tomorrow to double check it, then we should merge it.

**Review by philipturner — APPROVED** [review]

**Comment by philipturner** [comment]
> Ah ya, I agree with that route. Would that not make sense to live in this library though too?

It does sound convenient to have this in the library. However, the construct uses Swift concurrency which is not strictly related to numerical computing. It's a choice about us exposing the internals of the backend to the user. `numpy.ndarray` doesn't have hardware-acceleration either; it's just a CPU-backed type. And to reiterate, the Stdlib does not facilitate communication with external devices like bluetooth, networking, disk, GPU, etc. We could host the hardware implementation outside of `swift-shaped-array`, but that's linking the public API of something extremely general purpose with our specific numerics library.

Perhaps we can create async shaped arrays in another package, like "swift-async-shaped-array", which is tied closely to Matrix and interfaces with our chosen hardware accelerators. But at that point, we might want full API-internal access to an async shaped array's variables and methods, to maximize performance and do certain optimizations. We'll decide the most appropriate option once we reach that point.

**Pull request merged**
