### PR TITLE
Add primary associated type to _ShapedArrayProtocol

### PR DESCRIPTION
**Pull request by JaapWijnen**

### CODE REVIEW

**Review by rexmas — COMMENTED** [review]
Swift 5.7 hasn’t been released yet, I hesitate to merge code that relies on features in development branches

**Comment by JaapWijnen** [comment]
Ah that makes sense of course. We can hold this off until then? But I thought this also creates a space to discuss it if needed :)

**Comment by rexmas** [comment]
For sure, fwiw, I do agree with the change as soon as 5.7 is released :)

**Comment by philipturner** [comment]
Have you tested this on the Xcode 14 beta v5.7 release toolchain?

**Comment by ProfFan** [comment]
5.7 is released now I think?

**Comment by JaapWijnen** [comment]
Hah good point. Let's see if we can get some of this activity revived :) @rexmas good to merge?

**Comment by philipturner** [comment]
I'm not really planning to invest much time into the SWNG anymore, so I won't be reviewing PRs. But I wish you luck if you choose to keep the SWNG alive!

**Review by rexmas — APPROVED** [review]
ha yes!

**Pull request merged**
