### PR TITLE
Differentiable+backend

### PR DESCRIPTION
**Pull request by KhalidAl-otaibi**
Added three main things: 

1 - Differentiation for ShapedArray
2 - Basic Architecture (Operators -> CPU -> RawCPU) using sqrt function as an example. RawCPU could be replaced with Accelerate or MKL if specified.
3 - ShapedArrayFloatingPoint Protocol similar to TensorFlowFloatingPoint in S4TF

### CODE REVIEW

**Comment by KhalidAl-otaibi** [comment]
After a bit of thinking, I would like note that RawCPU, the default implementation is a huge undertaking and probably should be separated from the main project. The problem that this default implementation solves is that there is no BLAS-LAPLACK type library that is both open source and written in Swift AFAIK. There is Accelerate (probably written in Swift?) but not open source.

**Comment by JaapWijnen** [comment]
Hi! Thanks for the contribution! I have some comments/questions: 

- What are you currently using the swift-numerics dependency for?
- I'm not entirely sure what the ShapedArrayFloatingPointProtocol is for could you elaborate?

Thoughts:
- I don't think we should go for Differentiable support right from the beginning since Differentiation is still super experimental and this will for now limit usability for other people and add development time. I'd suggest getting a high quality basic type down first and then carefully introduce AutoDiff when ready. 
- If we would implement AutoDiff I'd suggest not depending on the Differentiation package that's currently in the dependencies since most people that are using autodiff as far as I know are on development toolchains anyway.

**Comment by rexmas** [comment]
It seems like there's a few different things emerging here.

@JaapWijnen 
> I don't think we should go for Differentiable support right from the beginning since Differentiation is still super experimental...I'd suggest getting a high quality basic type down first and then carefully introduce AutoDiff when ready.

Swift autodiff is one of the biggest strengths of using Swift for AI, at the same time I can't help but feel the same way from a project management perspective. Breaking things down to basic ShapedArray and then adding autodiff is going to create less uncertainty in getting things moving.

>  most people that are using autodiff as far as I know are on development toolchains anyway

How long is this intended to be the case? Will we need to maintain a development toolchain only branch that includes autodiff? That seems kind of bad, I'd almost be more inclined to invest time in improving autodiff and getting stable releases of it out once it comes to that point then.

@KhalidAl-otaibi 
> the default implementation is a huge undertaking. The problem that this default implementation solves is that there is no BLAS-LAPLACK type library that is both open source and written in Swift AFAIK

Again I think this choice is a simplification for project management. I frankly don't see it as that big of an undertaking, I could be wrong, but I imagine most of the operators are pretty simple to write (sans optimizations, let's not prematurely optimize). On the other hand, I'm not opposed to building on top of a C-lang BLAS-LAPACK if that seems more valuable, it just needs to at least run on both Mac and Linux minimum imo. The trade-off there is for operating systems the dependency is not compatible with the user will have no alternative. @JaapWijnen you have thoughts here too?

**Comment by KhalidAl-otaibi** [comment]
@rexmas 
> Again I think this choice is a simplification for project management. I frankly don't see it as that big of an undertaking, I could be wrong, but I imagine most of the operators are pretty simple to write (sans optimizations, let's not prematurely optimize). On the other hand, I'm not opposed to building on top of a C-lang BLAS-LAPACK if that seems more valuable, it just needs to at least run on both Mac and Linux minimum imo. The trade-off there is for operating systems the dependency is not compatible with the user will have no alternative.

Yeah, perhaps it's fairly doable and the benefits, I think, are worth it. Having a Swift BLAS-LAPLACK library would allow ShapedArray to run anywhere Swift runs, which is a major benefit. Also, not dealing with the headache of C dependancies on various architectures is a plus. 

Regarding differentiable, we could focus on that later, as @JaapWijnen suggested. For now we could focus on ShapedArray and the backend. 

> * What are you currently using the swift-numerics dependency for?
> * I'm not entirely sure what the ShapedArrayFloatingPointProtocol is for could you elaborate?

Numerics is necessary for the ElementaryFunctions protocol.

ShapedArrayFloatingPoint is meant to be a floating point type that conforms to Differentiable and ElementaryFunctions. Although, if we decide not support Differentiable for now, we don't need ShapedArrayFloatingPoint and we could use Real or Complex protocol provided by Numerics.

**Comment by rexmas** [comment]
Sounds like we're on the same page. Fwiw though, since a lot of users will want to run this on Linux (including myself) and Accelerate isn't there, at some point we'll need to find a BLAS-LAPLACK implementation. A C-lang one will be the likely candidate imo.

**Comment by KhalidAl-otaibi** [comment]
> Sounds like we're on the same page. Fwiw though, since a lot of users will want to run this on Linux (including myself) and Accelerate isn't there, at some point we'll need to find a BLAS-LAPLACK implementation. A C-lang one will be the likely candidate imo.

I think our default implementation written in Swift should follow the BLAS api as well, just because it's the standard in this kind of thing, while also allowing us to easily extend our code to other implementations of BLAS such as Accelerate later. Also, I found that there is an open source implementation of the BLAS-LAPLACK apis called OpenBLAS, so we could support that as well. It seems to have similar performance to MKL of intel while being open source and cross platform, so it could be a good choice.

**Comment by KhalidAl-otaibi** [comment]
I removed Differentiation for now as well as the ShapedArrayFloatingPoint protocol. I used Real protocol provided by Numerics instead.

**Comment by JaapWijnen** [comment]
@rexmas I'd argue we focus on Swift only for the moment, and prove we can create a useful api for this type. We can then start to think about optimisations when we run into performance bottlenecks. If the api itself is not useful at all then there's no use optimising in the background. So I'd suggest forgetting about backends for now and just write the swift logic and then start implementing benchmarks to see where our performance is lacking and making informed decisions from there. API is by far most important in my opinion since no-one is using the package yet. So I might even suggest not doing any abstraction like Backend/CPU called classes but just try and develop a good api that contains the direct swift functions to manipulate our internal storage. We'll get to abstracting that when we need it and when we know what we need in that case. Thoughts @rexmas 

Regarding numerics. I'm still not entirely sure why we'd need the swift-numerics protocols at the moment. I'd prefer the package to be as standalone as possible and only add in things that are 100% essential. @KhalidAl-otaibi  can you elaborate what you need the Real and Complex protocols for?

**Comment by KhalidAl-otaibi** [comment]
@JaapWijnen 
> Regarding numerics. I'm still not entirely sure why we'd need the swift-numerics protocols at the moment. I'd prefer the package to be as standalone as possible and only add in things that are 100% essential. @KhalidAl-otaibi can you elaborate what you need the Real and Complex protocols for?

It's used for avoiding redundancy and having to implement our own protocols. Instead of implementing the sqrt function for every floating point type (e.g. Float, Double, Float16, etc.), you just implement it a single time for the types conforming to the Real protocol.

**Comment by JaapWijnen** [comment]
@KhalidAl-otaibi you can use the FloatingPoint protocol for that: https://developer.apple.com/documentation/swift/floatingpoint

**Comment by rexmas** [comment]
> I'd argue we focus on Swift only for the moment, and prove we can create a useful api for this type

I agree with the approach you're suggesting 👍

**Comment by KhalidAl-otaibi** [comment]
> @KhalidAl-otaibi you can use the FloatingPoint protocol for that: https://developer.apple.com/documentation/swift/floatingpoint

@JaapWijnen 
Yeah but FloatingPoint does not have sqrt, and other important operators defined on it. So basically, how would you write code like this:
```Swift
extension ShapedArray where Scalar: Real {
    
    public static func sqrt(_ x: Self) -> Self {
        var ret = ShapedArray(repeating: 0, shape: x.shape)
        for i in 0..<x.scalarCount {
            // using buffer because ShapedArray does not allow subscripting yet
            ret.buffer[i] = .sqrt(x.buffer[i])
        }
        return ret
    }
}
```

Given, that sqrt is not defined over FloatingPoint, you need either use Real protocol or define your own type that conforms to FloatingPoint and then define sqrt and == and other operators on it.

**Comment by KhalidAl-otaibi** [comment]
Alright, I think we should close this PR. Since, we agreed that we should not focus on Differentiation for now. Also, that we should not abstract things for now and implement the functions on the API layer, essentially.

**Comment by JaapWijnen** [comment]
> Yeah but FloatingPoint does not have sqrt

It does, please read the documentation link I shared.

It has both a mutating (formSquareRoot()) and nonmutating method (squareRoot() -> Self)

**Comment by KhalidAl-otaibi** [comment]
Thank you for bearing with me and pointing this out!

**Comment by ProfFan** [comment]
I am doing Differentiable stuff in my fork, just FYI @KhalidAl-otaibi

**Comment by KhalidAl-otaibi** [comment]
Good stuff! I also wanted to conform ShapedArray to additive arithmetic but thought I should implement broadcastingPullback first.

**Comment by ProfFan** [comment]
@KhalidAl-otaibi You can see the current diff here: https://github.com/ProfFan/swift-shaped-array/pull/1/files

**Comment by JaapWijnen** [comment]
> 

No Problem! :)

**Comment by JaapWijnen** [comment]
> Thank you for bearing with me and pointing this out!

No problem! :) @KhalidAl-otaibi

**Pull request closed without merging**
